spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/数据库名?serverTimezone=GMT%2B8
    username: root
    password: root
    # 数据库连接池，spring默认hikari
    hikari:
      # 连接池的名称
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间默认10分钟(600000)，只有在连接数大于最小空闲连接时才生效
      idle-timeout: 1800000
      # 最大连接数
      maximum-pool-size: 10
      # 连接的最大生存时间
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时间
      connection-timeout: 30000
  redis:
    host: localhost
    port: 6379
    # 默认使用0号数据库
    database: 0
    timeout: 30000
    lettuce:
      # 连接池
      pool:
        # 最大连接数
        max-active: 10
        # 等待连接池分配连接的最大时间
        max-wait: 100000
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 4
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # 消费者的最小数量
        concurrency: 10
        # 消费者的最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息
        prefetch: 1

mybatis-plus:
  mapper-locations: classpath:com/ljn/demo/mapper/xml/*.xml
  type-aliases-package: com.ljn.demo.entity